const keysConfig = [
  { value: 'c2' },
  { value: 'd2', subValue: 'c#2' },
  { value: 'e2', subValue: 'd#2' },
  { value: 'f2', subValue: 'f#2' },
  { value: 'g2', subValue: 'g#2' },
  { value: 'a2', subValue: 'a#2' },
  { value: 'b2' },
  { value: 'c3' },
  { value: 'd3', subValue: 'c#3' },
  { value: 'e3', subValue: 'd#3' },
  { value: 'f3' },
  { value: 'g3', subValue: 'f#3' },
  { value: 'a3', subValue: 'g#3' },
  { value: 'b3', subValue: 'a#3' },
  { value: 'c4' },
  { value: 'd4', subValue: 'c#4' },
  { value: 'e4', subValue: 'd#4' },
  { value: 'f4' },
  { value: 'g4', subValue: 'f#4' },
  { value: 'a4', subValue: 'g#4' },
  { value: 'b4', subValue: 'a#4' },
  { value: 'c5' },
  { value: 'd5', subValue: 'c#5' },
  { value: 'e5', subValue: 'd#5' },
  { value: 'f5' },
  { value: 'g5', subValue: 'f#5' },
  { value: 'a5', subValue: 'g#5' },
  { value: 'b5', subValue: 'a#5' },
  { value: 'c6' },
  { value: 'd6', subValue: 'c#6' },
  { value: 'e6', subValue: 'd#6' },
  { value: 'f6' },
  { value: 'g6', subValue: 'f#6' },
  { value: 'a6', subValue: 'g#6' },
  { value: 'b6', subValue: 'a#6' },
  { value: 'c7' }
]

export default keysConfig
