const keysConfig = [
  { value: 'c2' },
  { value: 'd2', subValue: 'cs2' },
  { value: 'e2', subValue: 'ds2' },
  { value: 'f2' },
  { value: 'g2', subValue: 'fs2' },
  { value: 'a2', subValue: 'gs2' },
  { value: 'b2', subValue: 'as2' },
  { value: 'c3' },
  { value: 'd3', subValue: 'cs3' },
  { value: 'e3', subValue: 'ds3' },
  { value: 'f3' },
  { value: 'g3', subValue: 'fs3' },
  { value: 'a3', subValue: 'gs3' },
  { value: 'b3', subValue: 'as3' },
  { value: 'c4' },
  { value: 'd4', subValue: 'cs4' },
  { value: 'e4', subValue: 'ds4' },
  { value: 'f4' },
  { value: 'g4', subValue: 'fs4' },
  { value: 'a4', subValue: 'gs4' },
  { value: 'b4', subValue: 'as4' },
  { value: 'c5' },
  { value: 'd5', subValue: 'cs5' },
  { value: 'e5', subValue: 'ds5' },
  { value: 'f5' },
  { value: 'g5', subValue: 'fs5' },
  { value: 'a5', subValue: 'gs5' },
  { value: 'b5', subValue: 'as5' },
  { value: 'c6' },
  { value: 'd6', subValue: 'cs6' },
  { value: 'e6', subValue: 'ds6' },
  { value: 'f6' },
  { value: 'g6', subValue: 'fs6' },
  { value: 'a6', subValue: 'gs6' },
  { value: 'b6', subValue: 'as6' },
  { value: 'c7' }
]

export default keysConfig
